@host = http://localhost:8083
@userId = 1
@bookId = 10

### 도서 대여
POST {{host}}/rentals/{{userId}}/books/{{bookId}}

### 도서 반납
POST {{host}}/rentals/{{userId}}/items/{{bookId}}/return

### 대여 이력이 없는 사용자 도서 반납
POST {{host}}/rentals/999999/items/{{bookId}}/return
