apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: bookiverse
type: Opaque
stringData:
  book-username: book
  book-password: book
  rental-username: rental
  rental-password: rental
  user-username: user
  user-password: user
  root-password: root
