server:
  port: 8083

spring:
  application:
    name: rental
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rental
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    openfeign:
      client:
        config:
          book:
            url: http://localhost:8081
  datasource:
    url: jdbc:mysql://localhost:3308/rental?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: rental
    password: rental
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

rental:
  outbox:
    publisher:
      fixed-delay-ms: 1000
  overdue:
    scheduler:
      cron: "0 5 0 * * *"
