services:
  user-mysql:
    image: mysql:8.4
    container_name: user-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - user-mysql-data:/var/lib/mysql

volumes:
  user-mysql-data:
